import Navbar from './components/Navbar';
import './global.css';

export const metadata = {
  title: 'Welcome to sigdang',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      <link
        href="https://fonts.googleapis.com/css2?family=Lobster&display=swap"
        rel="stylesheet"
      ></link>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
